### ISSUE TITLE
(JOSS) Paper Contents

### ISSUE THREAD

**Issue by fb456** [TRACER-LULab/Hyperelastics.jl#121]
Hi,

In my opinion, there is no need to include the documentation Example in the paper's main body, despite it being very useful for the documentation. 

I think it would be helpful to add a brief, high-level description of the workflow (in words instead of code, maybe even graphically ), possibly mentioning the types of data being dealt with in the input/output. More emphasis on who the software is directed towards, as well as its scope in terms of what it can do would also be useful. In addition, it could be good to further emphasise the software's differences compared to other similar ones.

In the Example, there are some useful paragraphs in between the code parts, which could be compiled and further developed to address some of the issues above.

Let me know if any of the above is unclear.

**Comment by cfarm6** [comment]
@fb456 and @SotaYoshida Thank you. I have made updates to the paper to include a Use Case section for going over the highlights of the package and a section for comparisons with similar packages and features in other open-source and commercial programs

**Comment by fb456** [comment]
Hi @cfarm6.

Thanks. I think the new version of the paper addresses the issues mentioned above.
